export const ErrorCodes = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  FIELD_ERROR: "FIELD_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  RESOURCE_CONFLICT: "RESOURCE_CONFLICT",
  DUPLICATE_ENTITY: "DUPLICATE_ENTITY",
  OPERATION_ERROR: "OPERATION_ERROR",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  NETWORK_ERROR: "NETWORK_ERROR",
  NETWORK_TIMEOUT: "NETWORK_TIMEOUT",
  UNKNOWN_ERROR: "UNKNOWN_ERROR",

  CUSTOMER_NOT_FOUND: "CUSTOMER_NOT_FOUND",
  CUSTOMER_DUPLICATE: "CUSTOMER_DUPLICATE",
  LOAN_TYPE_NOT_FOUND: "LOAN_TYPE_NOT_FOUND",
  LOAN_APPLICATION_NOT_FOUND: "LOAN_APPLICATION_NOT_FOUND",
  INVALID_AMOUNT: "INVALID_AMOUNT",
  INVALID_TERM: "INVALID_TERM",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
