import type { TableEntity, Relationship } from "./schema.types";

// ─── LAYOUT: 5-column left-to-right dependency flow (Spacious 800px column gap) ───
//
//  Col 1 (x=60)     Col 2 (x=760)    Col 3 (x=1460)         Col 4 (x=2160)         Col 5 (x=2860)
//  ──────────────   ──────────────   ──────────────────────  ─────────────────────  ───────────────
//  document_types   users            customers              loan_applications      loans                  payment_installments
//  loan_types       roles            user_roles             auth_tokens
//  loan_app_status                   loan_app_status_history
//

export const SCHEMA_TABLES: TableEntity[] = [
  // ── COLUMNA 1: CATÁLOGOS / REFERENCIA (x=60) ─────────────────────────────
  {
    id: "document_types",
    name: "document_types",
    displayName: "Tipos de Documento",
    category: "referencia",
    description: "Catálogo de tipos de documento de identidad (CC, CE, NIT, etc.)",
    initialX: 60,
    initialY: 60,
    columns: [
      { name: "code", type: "VARCHAR(10)", isPk: true, nullable: false },
      { name: "name", type: "VARCHAR(100)", nullable: false },
      { name: "description", type: "VARCHAR(255)", nullable: true },
      { name: "created_at", type: "TIMESTAMPTZ", nullable: false },
      { name: "updated_at", type: "TIMESTAMPTZ", nullable: false },
    ],
  },
  {
    id: "loan_types",
    name: "loan_types",
    displayName: "Tipos de Préstamo",
    category: "referencia",
    description: "Modalidades de crédito: tasas, montos y plazos min/max",
    initialX: 60,
    initialY: 460,
    columns: [
      { name: "id", type: "UUID", isPk: true, nullable: false },
      { name: "name", type: "VARCHAR(100)", nullable: false },
      { name: "annual_interest_rate", type: "DECIMAL(5,2)", nullable: false },
      { name: "automatic_validation_enabled", type: "BOOLEAN", nullable: false },
      { name: "minimum_amount", type: "DECIMAL(15,2)", nullable: false },
      { name: "maximum_amount", type: "DECIMAL(15,2)", nullable: false },
      { name: "minimum_term_months", type: "INT", nullable: false },
      { name: "maximum_term_months", type: "INT", nullable: false },
      { name: "active", type: "BOOLEAN", nullable: false },
      { name: "created_at", type: "TIMESTAMPTZ", nullable: false },
      { name: "updated_at", type: "TIMESTAMPTZ", nullable: false },
    ],
  },
  {
    id: "loan_application_statuses",
    name: "loan_application_statuses",
    displayName: "Estados de Solicitud",
    category: "referencia",
    description: "Catálogo de estados para solicitudes de crédito",
    initialX: 60,
    initialY: 1000,
    columns: [
      { name: "code", type: "VARCHAR(20)", isPk: true, nullable: false },
      { name: "name", type: "VARCHAR(100)", nullable: false },
      { name: "description", type: "VARCHAR(255)", nullable: true },
      { name: "created_at", type: "TIMESTAMPTZ", nullable: false },
      { name: "updated_at", type: "TIMESTAMPTZ", nullable: false },
    ],
  },

  // ── COLUMNA 2: IDENTIDAD Y PERFIL (x=760) ────────────────────────────────
  {
    id: "users",
    name: "users",
    displayName: "Usuarios (Identidad)",
    category: "clientes",
    description: "Identidad, autenticación, roles y estado de acceso para todos los usuarios",
    initialX: 760,
    initialY: 60,
    columns: [
      { name: "id", type: "UUID", isPk: true, nullable: false },
      { name: "email", type: "VARCHAR(255)", nullable: false },
      { name: "password_hash", type: "VARCHAR(255)", nullable: false },
      { name: "role", type: "VARCHAR(20)", nullable: false },
      { name: "enabled", type: "BOOLEAN", nullable: false },
      { name: "failed_login_attempts", type: "INT", nullable: false },
      { name: "blocked_until", type: "TIMESTAMPTZ", nullable: true },
      { name: "last_login_at", type: "TIMESTAMPTZ", nullable: true },
      { name: "created_at", type: "TIMESTAMPTZ", nullable: false },
      { name: "updated_at", type: "TIMESTAMPTZ", nullable: false },
    ],
  },
  {
    id: "customers",
    name: "customers",
    displayName: "Clientes (Perfil)",
    category: "clientes",
    description: "Datos personales y financieros del cliente, separados de sus credenciales",
    initialX: 760,
    initialY: 760,
    columns: [
      { name: "id", type: "UUID", isPk: true, nullable: false },
      {
        name: "user_id",
        type: "UUID",
        isFk: true,
        fkTargetTable: "users",
        fkTargetColumn: "id",
        nullable: false,
      },
      { name: "first_name", type: "VARCHAR(100)", nullable: false },
      { name: "last_name", type: "VARCHAR(100)", nullable: false },
      {
        name: "document_type",
        type: "VARCHAR(10)",
        isFk: true,
        fkTargetTable: "document_types",
        fkTargetColumn: "code",
        nullable: false,
      },
      { name: "document_number", type: "VARCHAR(50)", nullable: false },
      { name: "base_salary", type: "DECIMAL(15,2)", nullable: false },
      { name: "phone", type: "VARCHAR(30)", nullable: true },
      { name: "created_at", type: "TIMESTAMPTZ", nullable: false },
      { name: "updated_at", type: "TIMESTAMPTZ", nullable: false },
    ],
  },
  {
    id: "roles",
    name: "roles",
    displayName: "Roles de Sistema",
    category: "staff",
    description: "Catálogo de roles con permisos (ADMIN, ANALYST, COLLECTOR)",
    initialX: 760,
    initialY: 860,
    columns: [
      { name: "id", type: "UUID", isPk: true, nullable: false },
      { name: "name", type: "VARCHAR(50)", nullable: false },
    ],
  },

  // ── COLUMNA 3: SOLICITUDES Y ROLES (x=1460) ──────────────────────────────
  {
    id: "loan_applications",
    name: "loan_applications",
    displayName: "Solicitudes de Préstamo",
    category: "prestamos",
    description: "Solicitudes ingresadas por los usuarios",
    initialX: 1460,
    initialY: 60,
    columns: [
      { name: "id", type: "UUID", isPk: true, nullable: false },
      {
        name: "customer_id",
        type: "UUID",
        isFk: true,
        fkTargetTable: "customers",
        fkTargetColumn: "id",
        nullable: false,
      },
      {
        name: "loan_type_id",
        type: "UUID",
        isFk: true,
        fkTargetTable: "loan_types",
        fkTargetColumn: "id",
        nullable: false,
      },
      {
        name: "status",
        type: "VARCHAR(20)",
        isFk: true,
        fkTargetTable: "loan_application_statuses",
        fkTargetColumn: "code",
        nullable: false,
      },
      { name: "annual_interest_rate", type: "DECIMAL(5,2)", nullable: false },
      { name: "requested_amount", type: "DECIMAL(15,2)", nullable: false },
      { name: "term_in_months", type: "INT", nullable: false },
      { name: "created_at", type: "TIMESTAMPTZ", nullable: false },
      { name: "updated_at", type: "TIMESTAMPTZ", nullable: false },
    ],
  },
  {
    id: "user_roles",
    name: "user_roles",
    displayName: "Roles de Usuario",
    category: "staff",
    description: "Asignación N:M de roles a usuarios del sistema (staff)",
    initialX: 1460,
    initialY: 680,
    columns: [
      {
        name: "user_id",
        type: "UUID",
        isPk: true,
        isFk: true,
        fkTargetTable: "users",
        fkTargetColumn: "id",
        nullable: false,
      },
      {
        name: "role_id",
        type: "UUID",
        isPk: true,
        isFk: true,
        fkTargetTable: "roles",
        fkTargetColumn: "id",
        nullable: false,
      },
    ],
  },
  {
    id: "loan_application_status_history",
    name: "loan_application_status_history",
    displayName: "Historial Estados Solicitud",
    category: "prestamos",
    description: "Trazabilidad histórica de los diferentes momentos y estados de las solicitudes",
    initialX: 1460,
    initialY: 900,
    columns: [
      { name: "id", type: "UUID", isPk: true, nullable: false },
      {
        name: "loan_application_id",
        type: "UUID",
        isFk: true,
        fkTargetTable: "loan_applications",
        fkTargetColumn: "id",
        nullable: false,
      },
      {
        name: "status",
        type: "VARCHAR(20)",
        isFk: true,
        fkTargetTable: "loan_application_statuses",
        fkTargetColumn: "code",
        nullable: false,
      },
      { name: "decision_reason", type: "VARCHAR(500)", nullable: true },
      {
        name: "evaluated_by",
        type: "UUID",
        isFk: true,
        fkTargetTable: "users",
        fkTargetColumn: "id",
        nullable: true,
      },
      { name: "opened_at", type: "TIMESTAMPTZ", nullable: false },
      { name: "closed_at", type: "TIMESTAMPTZ", nullable: true },
      { name: "created_at", type: "TIMESTAMPTZ", nullable: false },
      { name: "updated_at", type: "TIMESTAMPTZ", nullable: false },
    ],
  },

  // ── COLUMNA 4: PRÉSTAMOS ACTIVOS (x=2160) ────────────────────────────────
  {
    id: "loans",
    name: "loans",
    displayName: "Préstamos Vigentes",
    category: "prestamos",
    description: "Créditos aprobados y desembolsados en amortización",
    initialX: 2160,
    initialY: 60,
    columns: [
      { name: "id", type: "UUID", isPk: true, nullable: false },
      {
        name: "loan_application_id",
        type: "UUID",
        isFk: true,
        fkTargetTable: "loan_applications",
        fkTargetColumn: "id",
        nullable: false,
      },
      {
        name: "customer_id",
        type: "UUID",
        isFk: true,
        fkTargetTable: "customers",
        fkTargetColumn: "id",
        nullable: false,
      },
      { name: "principal_amount", type: "DECIMAL(15,2)", nullable: false },
      { name: "annual_interest_rate", type: "DECIMAL(5,2)", nullable: false },
      { name: "term_in_months", type: "INT", nullable: false },
      { name: "monthly_payment", type: "DECIMAL(15,2)", nullable: false },
      {
        name: "approved_by",
        type: "UUID",
        isFk: true,
        fkTargetTable: "users",
        fkTargetColumn: "id",
        nullable: true,
      },
      { name: "approved_at", type: "TIMESTAMPTZ", nullable: true },
      { name: "created_at", type: "TIMESTAMPTZ", nullable: false },
      { name: "updated_at", type: "TIMESTAMPTZ", nullable: false },
    ],
  },
  {
    id: "auth_tokens",
    name: "auth_tokens",
    displayName: "Tokens de Autenticación",
    category: "clientes",
    description: "Tokens de sesión (refresh) y restablecimiento de contraseña asociados a usuarios",
    initialX: 2160,
    initialY: 680,
    columns: [
      { name: "id", type: "UUID", isPk: true, nullable: false },
      {
        name: "user_id",
        type: "UUID",
        isFk: true,
        fkTargetTable: "users",
        fkTargetColumn: "id",
        nullable: false,
      },
      { name: "type", type: "VARCHAR(30)", nullable: false },
      { name: "token_hash", type: "VARCHAR(255)", nullable: false },
      { name: "expires_at", type: "TIMESTAMPTZ", nullable: false },
      { name: "revoked", type: "BOOLEAN", nullable: false },
      { name: "used", type: "BOOLEAN", nullable: false },
      { name: "created_at", type: "TIMESTAMPTZ", nullable: false },
      { name: "updated_at", type: "TIMESTAMPTZ", nullable: false },
    ],
  },

  // ── COLUMNA 5: TABLA DE AMORTIZACIÓN (x=2860) ────────────────────────────
  {
    id: "payment_installments",
    name: "payment_installments",
    displayName: "Cuotas de Pago",
    category: "prestamos",
    description: "Tabla de amortización y calendario de cuotas de cada préstamo",
    initialX: 2860,
    initialY: 60,
    columns: [
      { name: "id", type: "UUID", isPk: true, nullable: false },
      {
        name: "loan_id",
        type: "UUID",
        isFk: true,
        fkTargetTable: "loans",
        fkTargetColumn: "id",
        nullable: false,
      },
      { name: "installment_number", type: "INT", nullable: false },
      { name: "due_date", type: "DATE", nullable: false },
      { name: "opening_balance", type: "DECIMAL(15,2)", nullable: false },
      { name: "payment_amount", type: "DECIMAL(15,2)", nullable: false },
      { name: "principal_amount", type: "DECIMAL(15,2)", nullable: false },
      { name: "interest_amount", type: "DECIMAL(15,2)", nullable: false },
      { name: "closing_balance", type: "DECIMAL(15,2)", nullable: false },
      { name: "status", type: "VARCHAR(20)", nullable: false },
      { name: "paid_at", type: "TIMESTAMPTZ", nullable: true },
      { name: "created_at", type: "TIMESTAMPTZ", nullable: false },
      { name: "updated_at", type: "TIMESTAMPTZ", nullable: false },
    ],
  },
];

// ─── RELATIONSHIPS WITH EXPLICIT CARDINALITY ────────────────────────────────
export const SCHEMA_RELATIONSHIPS: Relationship[] = [
  // users (1) ── (0..1) customers
  {
    id: "rel_users_customers",
    fromTable: "users",
    fromColumn: "id",
    toTable: "customers",
    toColumn: "user_id",
    cardinality: "1:1",
    fromNotation: "1",
    toNotation: "0..1",
    description: "Un usuario puede tener opcionalmente un perfil de cliente",
  },
  // document_types (1) ── (0..N) customers
  {
    id: "rel_doc_types_users",
    fromTable: "document_types",
    fromColumn: "code",
    toTable: "customers",
    toColumn: "document_type",
    cardinality: "1:N",
    fromNotation: "1",
    toNotation: "0..N",
    description: "Un tipo de documento aplica a múltiples clientes",
  },
  // users (1) ── (0..N) user_roles
  {
    id: "rel_users_user_roles",
    fromTable: "users",
    fromColumn: "id",
    toTable: "user_roles",
    toColumn: "user_id",
    cardinality: "1:N",
    fromNotation: "1",
    toNotation: "0..N",
    description: "Un usuario puede tener múltiples roles asignados",
  },
  // roles (1) ── (0..N) user_roles
  {
    id: "rel_roles_user_roles",
    fromTable: "roles",
    fromColumn: "id",
    toTable: "user_roles",
    toColumn: "role_id",
    cardinality: "1:N",
    fromNotation: "1",
    toNotation: "0..N",
    description: "Un rol puede asignarse a múltiples usuarios del sistema",
  },
  // users (1) ── (0..N) auth_tokens
  {
    id: "rel_users_auth_tokens",
    fromTable: "users",
    fromColumn: "id",
    toTable: "auth_tokens",
    toColumn: "user_id",
    cardinality: "1:N",
    fromNotation: "1",
    toNotation: "0..N",
    description: "Un usuario genera múltiples tokens de sesión o recuperación",
  },
  // customers (1) ── (0..N) loan_applications
  {
    id: "rel_customers_applications",
    fromTable: "customers",
    fromColumn: "id",
    toTable: "loan_applications",
    toColumn: "customer_id",
    cardinality: "1:N",
    fromNotation: "1",
    toNotation: "0..N",
    description: "Un cliente puede radicar múltiples solicitudes de crédito",
  },
  // loan_types (1) ── (0..N) loan_applications
  {
    id: "rel_loan_types_applications",
    fromTable: "loan_types",
    fromColumn: "id",
    toTable: "loan_applications",
    toColumn: "loan_type_id",
    cardinality: "1:N",
    fromNotation: "1",
    toNotation: "0..N",
    description: "Cada tipo de préstamo clasifica múltiples solicitudes",
  },
  // loan_application_statuses (1) ── (0..N) loan_applications
  {
    id: "rel_statuses_applications",
    fromTable: "loan_application_statuses",
    fromColumn: "code",
    toTable: "loan_applications",
    toColumn: "status",
    cardinality: "1:N",
    fromNotation: "1",
    toNotation: "0..N",
    description: "Cada estado de solicitud agrupa múltiples solicitudes",
  },
  // loan_applications (1) ── (1..N) loan_application_status_history
  {
    id: "rel_applications_history",
    fromTable: "loan_applications",
    fromColumn: "id",
    toTable: "loan_application_status_history",
    toColumn: "loan_application_id",
    cardinality: "1:N",
    fromNotation: "1",
    toNotation: "1..N",
    description: "Una solicitud registra su historia de cambios de estado",
  },
  // loan_application_statuses (1) ── (0..N) loan_application_status_history
  {
    id: "rel_statuses_history",
    fromTable: "loan_application_statuses",
    fromColumn: "code",
    toTable: "loan_application_status_history",
    toColumn: "status",
    cardinality: "1:N",
    fromNotation: "1",
    toNotation: "0..N",
    description: "Un estado catálogo aparece múltiples veces en la historia",
  },
  // users (1) ── (0..N) loan_application_status_history [evaluated_by]
  {
    id: "rel_users_status_history_evaluator",
    fromTable: "users",
    fromColumn: "id",
    toTable: "loan_application_status_history",
    toColumn: "evaluated_by",
    cardinality: "1:N",
    fromNotation: "1",
    toNotation: "0..N",
    description: "Un usuario evaluador emite decisiones sobre distintas solicitudes",
  },
  // loan_applications (1) ── (0..1) loans
  {
    id: "rel_applications_loans",
    fromTable: "loan_applications",
    fromColumn: "id",
    toTable: "loans",
    toColumn: "loan_application_id",
    cardinality: "1:1",
    fromNotation: "1",
    toNotation: "0..1",
    description: "Una solicitud aprobada origina exactamente un préstamo desembolsado",
  },
  // customers (1) ── (0..N) loans
  {
    id: "rel_customers_loans",
    fromTable: "customers",
    fromColumn: "id",
    toTable: "loans",
    toColumn: "customer_id",
    cardinality: "1:N",
    fromNotation: "1",
    toNotation: "0..N",
    description: "Un cliente posee y responde por múltiples préstamos vigentes",
  },
  // users (1) ── (0..N) loans [approved_by]
  {
    id: "rel_users_loans_approver",
    fromTable: "users",
    fromColumn: "id",
    toTable: "loans",
    toColumn: "approved_by",
    cardinality: "1:N",
    fromNotation: "1",
    toNotation: "0..N",
    description: "Un usuario staff aprueba y autoriza múltiples préstamos",
  },
  // loans (1) ── (1..N) payment_installments
  {
    id: "rel_loans_installments",
    fromTable: "loans",
    fromColumn: "id",
    toTable: "payment_installments",
    toColumn: "loan_id",
    cardinality: "1:N",
    fromNotation: "1",
    toNotation: "1..N",
    description: "Un préstamo amortiza su deuda a través de múltiples cuotas de pago",
  },
];
