app:
  security:
    cookie:
      secure: true

spring:
  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
